### ISSUE TITLE
Not a real issue but a request

### ISSUE THREAD

**Issue by peppeve** [hxim/paq8px#111]
It is possible to add the function to compress a folder like the version 124. Thank's.

**Comment by GotthardtZ** [comment]
Paq8px still supports folder compression. But differently.
Since v137 you have to provide a list of files you wish to compress. The list may contain file names (file.ext) or file names in folders or in subfolders (folder/file.ext, folder/folder/file.ext).

Why the change?
Paq8px is sensitive to the name of the files and the order they are compressed, so the names of files and the order they are added to the archive is completely in your hands since v137.
From the CHANGELOG: in v137: "Wildcard support and folder compression is removed for the sake of a list-based file enumeration."

See also the help screen:
   INPUTSPEC:
   The input may be a FILE or a PATH/FILE or a [PATH/]@FILELIST.
   Only file content and the file size is kept in the archive. Filename,
   path, date and any file attributes or permissions are not stored.
   When a @FILELIST is provided the FILELIST file will be considered
   implicitly as the very first input file. It will be compressed and upon
   decompression it will be extracted. The FILELIST is a tab separated text
   file where the first column contains the names and optionally the relative
   paths of the files to be compressed. The paths should be relative to the
   FILELIST file. In the other columns you may store any information you wish
   to keep about the files (timestamp, owner, attributes or your own remarks).
   These extra columns will be ignored by the compressor and the decompressor
   but you may restore full file information using them with a 3rd party
   utility. The FILELIST file must contain a header but will be ignored.

A little bit more about the structure of the list of files:
https://encode.ru/threads/342-paq8px?p=58971&viewfull=1#post58971

If you find it cumbersome to create a list of files from a folder, you may use the PAQCompress GUI from Moises Cardona located at https://github.com/moisesmcardona/PAQCompress. It will help you creating the file list from a folder automatically.

**Comment by moisesmcardona** [comment]
I also have a command-line utility that helps doing this as well. It's written in Python 3:   https://github.com/moisesmcardona/paq8px_scripts

**Comment by GotthardtZ** [comment]
I believe this issue may be closed.
